name: bitreq - unit tests

on:
  push:
    branches: [ master ]
    paths:
      - 'bitreq/**'
      - '.github/workflows/bitreq-unit-tests.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'bitreq/**'
      - '.github/workflows/bitreq-unit-tests.yml'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: bitreq

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build
    - name: Test
      run: |
        cargo test
        cargo test --features punycode
        cargo test --features proxy
        cargo test --features urlencoding
        cargo test --features https
  test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build
    - name: Test
      run: |
        cargo test
        cargo test --features punycode
        cargo test --features proxy
        cargo test --features urlencoding
        cargo test --features https
        cargo test --features "punycode proxy urlencoding https"
  test-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build
    - name: Test
      run: |
        cargo test
        cargo test --features punycode
        cargo test --features proxy
        cargo test --features urlencoding
        cargo test --features https
        cargo test --features "punycode proxy urlencoding https"
