name: msrv

on:
  push:
    branches: [ master ]
    paths:
      - 'bitreq/**'
      - '.github/workflows/bitreq-msrv.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'bitreq/**'
      - '.github/workflows/bitreq-msrv.yml'
  schedule:
    - cron: "47 5 * * 6"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: bitreq

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@1.63
      - name: Running test script
        run: |
          cargo test
